[template]
src = "docker-registry.yml.tmpl"
dest = "/etc/docker-registry.yml"
keys = [
  "BALENA_REGISTRY2_HOST",
  "BALENA_TOKEN_AUTH_REALM",
  "BALENA_TOKEN_AUTH_ISSUER",
  "COMMON_REGION",
  "REGISTRY2_CACHE_ENABLED",
  "REGISTRY2_CACHE_ADDR",
  "REGISTRY2_CACHE_DB",
  "REGISTRY2_S3_CLOUDFRONT_KEYPAIR_ID",
  "REGISTRY2_S3_CLOUDFRONT_ENDPOINT",
  "REGISTRY2_S3_BUCKET",
  "REGISTRY2_S3_KEY",
  "REGISTRY2_S3_REGION_ENDPOINT",
  "REGISTRY2_S3_SECRET",
  "REGISTRY2_SECRETKEY",
  "REGISTRY2_STORAGEPATH",
]
